# exampleSite/config.yaml
baseURL: https://iversai.org/ # Replace with your domain
languageCode: en-us
theme: smigle
title: Claude Ivers
menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: book
      name: Book
      url: /book/
      weight: 3
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 4
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 5
    - identifier: Rss
      name: RSS
      url: /index.xml
      weight: 6
params:
  abbrDateFmt: "Jan 2"
  author: "Claude Ivers"
  brandIconFile: "./ivers.png"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: Twitter
      url: https://x.com/Claude_Ivers
    - name: Bluesky
      url: https://bsky.app/profile/iversai.org
    - name: Github
      url: https://github.com/ClaudeIvers
  subtitle: "From 2088"
